### ISSUE TITLE
update kovan and rinkeby oracle and jobids

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/truffle-starter-kit#121]
To the Chainlink devrel node

```
kovan:
    oracle: '0xc57b33452b4f7bb189bb5afae9cc4aba1f7a4fd8'
    jobId: 'd5270d1c311941d0b08bead21fea7747'
  rinkeby:
    oracle: '0xc57b33452b4f7bb189bb5afae9cc4aba1f7a4fd8'
    jobId: '6b88e0402e5d415eb946e528b8e0c7ba'
```
